services:
  # PostgreSQL cho blog-media
  postgres-media:
    image: postgres:15-alpine
    container_name: blog-postgres-media
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-media-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - blog-network

  # MinIO cho lưu trữ media
  minio:
    image: quay.io/minio/minio:latest
    container_name: blog-minio
    ports:
      - "9000:9000"   # API port
      - "9001:9001"   # Console port
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped
    networks:
      - blog-network

  # Blog Media Service
  blog-media:
    build:
      context: ..
      dockerfile: blog-media/Dockerfile
    container_name: blog-media-service
    depends_on:
      postgres-media:
        condition: service_healthy
      minio:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SERVER_PORT=${MEDIA_SERVER_PORT}
      - SPRING_DATASOURCE_URL=${SPRING_MEDIA_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_MEDIA_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_MEDIA_DATASOURCE_PASSWORD}
      - SPRING_REDIS_HOST=${SPRING_REDIS_HOST}
      - SPRING_REDIS_PORT=${SPRING_REDIS_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - MINIO_URL=${MINIO_URL}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      - EUREKA_SERVER=${EUREKA_SERVER}
    ports:
      - "${MEDIA_SERVER_PORT}:${MEDIA_SERVER_PORT}"
    restart: unless-stopped
    networks:
      - blog-network

volumes:
  postgres-media-data:
    name: blog-postgres-media-data
  minio-data:
    name: blog-minio-data

networks:
  blog-network:
    name: blog-network
    external: true 